# Generated by Django 5.2.11 on 2026-03-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('player1_name', models.CharField(max_length=100)),
                ('player2_name', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
